# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
