# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20180302_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='gallery_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
