# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
