# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20180311_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='for_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instagram.Image'),
        ),
    ]
